set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_VERSION 11)

if(NOT DEFINED ENV{PS5_PAYLOAD_SDK})
  message(FATAL_ERROR "PS5_PAYLOAD_SDK is undefined")
else()
  set(PS5_PAYLOAD_SDK $ENV{PS5_PAYLOAD_SDK})
endif()

set(CMAKE_CROSSCOMPILING 1)

set(CMAKE_SYSROOT ${PS5_PAYLOAD_SDK})
set(CMAKE_ASM_COMPILER ${PS5_PAYLOAD_SDK}/host/x86_64-ps5-payload-cc)
set(CMAKE_C_COMPILER ${PS5_PAYLOAD_SDK}/host/x86_64-ps5-payload-cc)
set(CMAKE_CXX_COMPILER ${PS5_PAYLOAD_SDK}/host/x86_64-ps5-payload-cxx)

set(CMAKE_POSITION_INDEPENDENT_CODE ON)

set(CMAKE_EXE_LINKER_FLAGS "-pie")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -nostartfiles")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -nostdlib")
string(APPEND CMAKE_EXE_LINKER_FLAGS " ${PS5_PAYLOAD_SDK}/usr/lib/crt1.o")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -T${PS5_PAYLOAD_SDK}/ldscripts/elf_x86_64.x")
