#!/usr/bin/env bash
#   Copyright (C) 2024 John Törnblom
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not see
# <http://www.gnu.org/licenses/>.

if [[ -z "$PS5_HOST" ]]; then
    PS5_HOST=ps5
fi

if [[ -z "$PS5_PORT" ]]; then
    PS5_PORT=9021
fi

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <PATH>"
    exit 1
fi

netcat -q0 -v $PS5_HOST $PS5_PORT < $1
