#!/usr/bin/env bash
#   Copyright (C) 2023 John Törnblom
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not see
# <http://www.gnu.org/licenses/>.

PS5_PAYLOAD_SDK="${BASH_SOURCE[0]}"
PS5_PAYLOAD_SDK="$(dirname "${PS5_PAYLOAD_SDK}")"
PS5_PAYLOAD_SDK="${PS5_PAYLOAD_SDK}/.."

if [[ -z "$PS5_TARGET_TRIPLE" ]]; then
    PS5_TARGET_TRIPLE=x86_64-pc-none
fi

CANDIDATES=("clang-17"
            "clang-16"
            "clang-15")

for CC in "${CANDIDATES[@]}"; do
    if [ -x "$(command -v $CC)" ]; then
	exec $CC \
	     -target $PS5_TARGET_TRIPLE \
	     -fPIE -fno-stack-protector -ffreestanding -fno-builtin -nostdlib \
	     $*
    fi
done

exit 1

