#!/usr/bin/env bash
#   Copyright (C) 2023 John Törnblom
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not see
# <http://www.gnu.org/licenses/>.

PS5_PAYLOAD_SDK="${BASH_SOURCE[0]}"
PS5_PAYLOAD_SDK="$(dirname "${PS5_PAYLOAD_SDK}")"
PS5_PAYLOAD_SDK="${PS5_PAYLOAD_SDK}/.."

CANDIDATES=("ld.lld-17"
            "ld.lld-16"
            "ld.lld-15")

for LD in "${CANDIDATES[@]}"; do
    if [ -x "$(command -v $LD)" ]; then
	exec $LD \
	     -pie \
	     -T "${PS5_PAYLOAD_SDK}/ldscripts/elf_x86_64.x" \
	     -L "${PS5_PAYLOAD_SDK}/usr/lib" \
	     $* \
	     "${PS5_PAYLOAD_SDK}/usr/lib/crt1.o"
    fi
done

exit 1
