/*
 This file was generated by trampgen.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);

static __attribute__ ((used)) void* __ptr_sceSystemServiceAcquireBgmCpuBudget;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceAcquireBgmCpuBudget\n"
    ".type sceSystemServiceAcquireBgmCpuBudget @function\n"
    "sceSystemServiceAcquireBgmCpuBudget:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceAcquireBgmCpuBudget]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceAcquireFb0;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceAcquireFb0\n"
    ".type sceSystemServiceAcquireFb0 @function\n"
    "sceSystemServiceAcquireFb0:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceAcquireFb0]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceAddLocalProcess;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceAddLocalProcess\n"
    ".type sceSystemServiceAddLocalProcess @function\n"
    "sceSystemServiceAddLocalProcess:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceAddLocalProcess]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceAddLocalProcessForPsmKit;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceAddLocalProcessForPsmKit\n"
    ".type sceSystemServiceAddLocalProcessForPsmKit @function\n"
    "sceSystemServiceAddLocalProcessForPsmKit:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceAddLocalProcessForPsmKit]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceAppGetAppInstallStatus;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceAppGetAppInstallStatus\n"
    ".type sceSystemServiceAppGetAppInstallStatus @function\n"
    "sceSystemServiceAppGetAppInstallStatus:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceAppGetAppInstallStatus]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeAcpClock;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeAcpClock\n"
    ".type sceSystemServiceChangeAcpClock @function\n"
    "sceSystemServiceChangeAcpClock:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeAcpClock]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeClock;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeClock\n"
    ".type sceSystemServiceChangeClock @function\n"
    "sceSystemServiceChangeClock:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeClock]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeCpuClock;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeCpuClock\n"
    ".type sceSystemServiceChangeCpuClock @function\n"
    "sceSystemServiceChangeCpuClock:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeCpuClock]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeCpuPstate;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeCpuPstate\n"
    ".type sceSystemServiceChangeCpuPstate @function\n"
    "sceSystemServiceChangeCpuPstate:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeCpuPstate]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeGpuClock;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeGpuClock\n"
    ".type sceSystemServiceChangeGpuClock @function\n"
    "sceSystemServiceChangeGpuClock:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeGpuClock]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeMemPstate;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeMemPstate\n"
    ".type sceSystemServiceChangeMemPstate @function\n"
    "sceSystemServiceChangeMemPstate:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeMemPstate]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeMemoryClock;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeMemoryClock\n"
    ".type sceSystemServiceChangeMemoryClock @function\n"
    "sceSystemServiceChangeMemoryClock:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeMemoryClock]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeMemoryClockToBaseMode;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeMemoryClockToBaseMode\n"
    ".type sceSystemServiceChangeMemoryClockToBaseMode @function\n"
    "sceSystemServiceChangeMemoryClockToBaseMode:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeMemoryClockToBaseMode]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeMemoryClockToDefault;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeMemoryClockToDefault\n"
    ".type sceSystemServiceChangeMemoryClockToDefault @function\n"
    "sceSystemServiceChangeMemoryClockToDefault:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeMemoryClockToDefault]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeMemoryClockToMultiMediaMode;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeMemoryClockToMultiMediaMode\n"
    ".type sceSystemServiceChangeMemoryClockToMultiMediaMode @function\n"
    "sceSystemServiceChangeMemoryClockToMultiMediaMode:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeMemoryClockToMultiMediaMode]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeNumberOfGpuCu;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeNumberOfGpuCu\n"
    ".type sceSystemServiceChangeNumberOfGpuCu @function\n"
    "sceSystemServiceChangeNumberOfGpuCu:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeNumberOfGpuCu]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeSamuClock;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeSamuClock\n"
    ".type sceSystemServiceChangeSamuClock @function\n"
    "sceSystemServiceChangeSamuClock:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeSamuClock]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeUvdClock;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeUvdClock\n"
    ".type sceSystemServiceChangeUvdClock @function\n"
    "sceSystemServiceChangeUvdClock:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeUvdClock]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceChangeVceClock;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceChangeVceClock\n"
    ".type sceSystemServiceChangeVceClock @function\n"
    "sceSystemServiceChangeVceClock:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceChangeVceClock]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceDisableMediaPlay;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceDisableMediaPlay\n"
    ".type sceSystemServiceDisableMediaPlay @function\n"
    "sceSystemServiceDisableMediaPlay:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceDisableMediaPlay]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceDisableMusicPlayer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceDisableMusicPlayer\n"
    ".type sceSystemServiceDisableMusicPlayer @function\n"
    "sceSystemServiceDisableMusicPlayer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceDisableMusicPlayer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceDisableNoticeScreenSkipFlagAutoSet;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceDisableNoticeScreenSkipFlagAutoSet\n"
    ".type sceSystemServiceDisableNoticeScreenSkipFlagAutoSet @function\n"
    "sceSystemServiceDisableNoticeScreenSkipFlagAutoSet:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceDisableNoticeScreenSkipFlagAutoSet]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceDisablePersonalEyeToEyeDistanceSetting;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceDisablePersonalEyeToEyeDistanceSetting\n"
    ".type sceSystemServiceDisablePersonalEyeToEyeDistanceSetting @function\n"
    "sceSystemServiceDisablePersonalEyeToEyeDistanceSetting:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceDisablePersonalEyeToEyeDistanceSetting]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceDisableSuspendConfirmationDialog;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceDisableSuspendConfirmationDialog\n"
    ".type sceSystemServiceDisableSuspendConfirmationDialog @function\n"
    "sceSystemServiceDisableSuspendConfirmationDialog:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceDisableSuspendConfirmationDialog]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceEnablePersonalEyeToEyeDistanceSetting;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceEnablePersonalEyeToEyeDistanceSetting\n"
    ".type sceSystemServiceEnablePersonalEyeToEyeDistanceSetting @function\n"
    "sceSystemServiceEnablePersonalEyeToEyeDistanceSetting:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceEnablePersonalEyeToEyeDistanceSetting]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceEnableSuspendConfirmationDialog;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceEnableSuspendConfirmationDialog\n"
    ".type sceSystemServiceEnableSuspendConfirmationDialog @function\n"
    "sceSystemServiceEnableSuspendConfirmationDialog:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceEnableSuspendConfirmationDialog]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetAppCategoryType;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetAppCategoryType\n"
    ".type sceSystemServiceGetAppCategoryType @function\n"
    "sceSystemServiceGetAppCategoryType:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetAppCategoryType]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetAppFocusedAppStatus;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetAppFocusedAppStatus\n"
    ".type sceSystemServiceGetAppFocusedAppStatus @function\n"
    "sceSystemServiceGetAppFocusedAppStatus:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetAppFocusedAppStatus]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetAppId;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetAppId\n"
    ".type sceSystemServiceGetAppId @function\n"
    "sceSystemServiceGetAppId:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetAppId]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetAppIdListOfBigApp;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetAppIdListOfBigApp\n"
    ".type sceSystemServiceGetAppIdListOfBigApp @function\n"
    "sceSystemServiceGetAppIdListOfBigApp:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetAppIdListOfBigApp]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetAppIdOfRunningBigApp;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetAppIdOfRunningBigApp\n"
    ".type sceSystemServiceGetAppIdOfRunningBigApp @function\n"
    "sceSystemServiceGetAppIdOfRunningBigApp:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetAppIdOfRunningBigApp]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetAppLaunchedUser;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetAppLaunchedUser\n"
    ".type sceSystemServiceGetAppLaunchedUser @function\n"
    "sceSystemServiceGetAppLaunchedUser:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetAppLaunchedUser]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetAppStatus;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetAppStatus\n"
    ".type sceSystemServiceGetAppStatus @function\n"
    "sceSystemServiceGetAppStatus:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetAppStatus]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetAppTitleId;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetAppTitleId\n"
    ".type sceSystemServiceGetAppTitleId @function\n"
    "sceSystemServiceGetAppTitleId:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetAppTitleId]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetAppType;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetAppType\n"
    ".type sceSystemServiceGetAppType @function\n"
    "sceSystemServiceGetAppType:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetAppType]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetDisplaySafeAreaInfo;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetDisplaySafeAreaInfo\n"
    ".type sceSystemServiceGetDisplaySafeAreaInfo @function\n"
    "sceSystemServiceGetDisplaySafeAreaInfo:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetDisplaySafeAreaInfo]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetEventForDaemon;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetEventForDaemon\n"
    ".type sceSystemServiceGetEventForDaemon @function\n"
    "sceSystemServiceGetEventForDaemon:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetEventForDaemon]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetGpuLoadEmulationMode;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetGpuLoadEmulationMode\n"
    ".type sceSystemServiceGetGpuLoadEmulationMode @function\n"
    "sceSystemServiceGetGpuLoadEmulationMode:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetGpuLoadEmulationMode]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetHdrToneMapLuminance;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetHdrToneMapLuminance\n"
    ".type sceSystemServiceGetHdrToneMapLuminance @function\n"
    "sceSystemServiceGetHdrToneMapLuminance:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetHdrToneMapLuminance]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetLocalProcessStatusList;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetLocalProcessStatusList\n"
    ".type sceSystemServiceGetLocalProcessStatusList @function\n"
    "sceSystemServiceGetLocalProcessStatusList:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetLocalProcessStatusList]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetMainAppTitleId;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetMainAppTitleId\n"
    ".type sceSystemServiceGetMainAppTitleId @function\n"
    "sceSystemServiceGetMainAppTitleId:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetMainAppTitleId]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetNoticeScreenSkipFlag;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetNoticeScreenSkipFlag\n"
    ".type sceSystemServiceGetNoticeScreenSkipFlag @function\n"
    "sceSystemServiceGetNoticeScreenSkipFlag:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetNoticeScreenSkipFlag]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetPSButtonEvent;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetPSButtonEvent\n"
    ".type sceSystemServiceGetPSButtonEvent @function\n"
    "sceSystemServiceGetPSButtonEvent:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetPSButtonEvent]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetParentSocket;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetParentSocket\n"
    ".type sceSystemServiceGetParentSocket @function\n"
    "sceSystemServiceGetParentSocket:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetParentSocket]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetParentSocketForPsmKit;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetParentSocketForPsmKit\n"
    ".type sceSystemServiceGetParentSocketForPsmKit @function\n"
    "sceSystemServiceGetParentSocketForPsmKit:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetParentSocketForPsmKit]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetRemoteplayStatus;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetRemoteplayStatus\n"
    ".type sceSystemServiceGetRemoteplayStatus @function\n"
    "sceSystemServiceGetRemoteplayStatus:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetRemoteplayStatus]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetRenderingMode;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetRenderingMode\n"
    ".type sceSystemServiceGetRenderingMode @function\n"
    "sceSystemServiceGetRenderingMode:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetRenderingMode]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetStatus;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetStatus\n"
    ".type sceSystemServiceGetStatus @function\n"
    "sceSystemServiceGetStatus:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetStatus]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetSubAppTitleId;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetSubAppTitleId\n"
    ".type sceSystemServiceGetSubAppTitleId @function\n"
    "sceSystemServiceGetSubAppTitleId:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetSubAppTitleId]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetSubAppTitleIdForSP;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetSubAppTitleIdForSP\n"
    ".type sceSystemServiceGetSubAppTitleIdForSP @function\n"
    "sceSystemServiceGetSubAppTitleIdForSP:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetSubAppTitleIdForSP]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetTitleWorkaroundInfo;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetTitleWorkaroundInfo\n"
    ".type sceSystemServiceGetTitleWorkaroundInfo @function\n"
    "sceSystemServiceGetTitleWorkaroundInfo:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetTitleWorkaroundInfo]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetUIStatus;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetUIStatus\n"
    ".type sceSystemServiceGetUIStatus @function\n"
    "sceSystemServiceGetUIStatus:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetUIStatus]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceGetVersionNumberOfCameraCalibrationData;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceGetVersionNumberOfCameraCalibrationData\n"
    ".type sceSystemServiceGetVersionNumberOfCameraCalibrationData @function\n"
    "sceSystemServiceGetVersionNumberOfCameraCalibrationData:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceGetVersionNumberOfCameraCalibrationData]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceHideSplashScreen;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceHideSplashScreen\n"
    ".type sceSystemServiceHideSplashScreen @function\n"
    "sceSystemServiceHideSplashScreen:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceHideSplashScreen]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceInitializePlayerDialogParam;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceInitializePlayerDialogParam\n"
    ".type sceSystemServiceInitializePlayerDialogParam @function\n"
    "sceSystemServiceInitializePlayerDialogParam:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceInitializePlayerDialogParam]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceIsAppSuspended;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceIsAppSuspended\n"
    ".type sceSystemServiceIsAppSuspended @function\n"
    "sceSystemServiceIsAppSuspended:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceIsAppSuspended]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceIsBgmCpuBudgetAvailable;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceIsBgmCpuBudgetAvailable\n"
    ".type sceSystemServiceIsBgmCpuBudgetAvailable @function\n"
    "sceSystemServiceIsBgmCpuBudgetAvailable:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceIsBgmCpuBudgetAvailable]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceIsBgmPlaying;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceIsBgmPlaying\n"
    ".type sceSystemServiceIsBgmPlaying @function\n"
    "sceSystemServiceIsBgmPlaying:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceIsBgmPlaying]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceIsEyeToEyeDistanceAdjusted;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceIsEyeToEyeDistanceAdjusted\n"
    ".type sceSystemServiceIsEyeToEyeDistanceAdjusted @function\n"
    "sceSystemServiceIsEyeToEyeDistanceAdjusted:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceIsEyeToEyeDistanceAdjusted]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceIsGameLiveStreamingOnAir;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceIsGameLiveStreamingOnAir\n"
    ".type sceSystemServiceIsGameLiveStreamingOnAir @function\n"
    "sceSystemServiceIsGameLiveStreamingOnAir:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceIsGameLiveStreamingOnAir]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceIsScreenSaverOn;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceIsScreenSaverOn\n"
    ".type sceSystemServiceIsScreenSaverOn @function\n"
    "sceSystemServiceIsScreenSaverOn:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceIsScreenSaverOn]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceIsShellUiFgAndGameBgCpuMode;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceIsShellUiFgAndGameBgCpuMode\n"
    ".type sceSystemServiceIsShellUiFgAndGameBgCpuMode @function\n"
    "sceSystemServiceIsShellUiFgAndGameBgCpuMode:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceIsShellUiFgAndGameBgCpuMode]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceKillApp;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceKillApp\n"
    ".type sceSystemServiceKillApp @function\n"
    "sceSystemServiceKillApp:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceKillApp]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceKillLocalProcess;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceKillLocalProcess\n"
    ".type sceSystemServiceKillLocalProcess @function\n"
    "sceSystemServiceKillLocalProcess:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceKillLocalProcess]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceKillLocalProcessForPsmKit;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceKillLocalProcessForPsmKit\n"
    ".type sceSystemServiceKillLocalProcessForPsmKit @function\n"
    "sceSystemServiceKillLocalProcessForPsmKit:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceKillLocalProcessForPsmKit]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceLaunchApp;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceLaunchApp\n"
    ".type sceSystemServiceLaunchApp @function\n"
    "sceSystemServiceLaunchApp:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceLaunchApp]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceLaunchEventDetails;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceLaunchEventDetails\n"
    ".type sceSystemServiceLaunchEventDetails @function\n"
    "sceSystemServiceLaunchEventDetails:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceLaunchEventDetails]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceLaunchPlayerDialog;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceLaunchPlayerDialog\n"
    ".type sceSystemServiceLaunchPlayerDialog @function\n"
    "sceSystemServiceLaunchPlayerDialog:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceLaunchPlayerDialog]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceLaunchTournamentList;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceLaunchTournamentList\n"
    ".type sceSystemServiceLaunchTournamentList @function\n"
    "sceSystemServiceLaunchTournamentList:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceLaunchTournamentList]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceLaunchTournamentsTeamProfile;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceLaunchTournamentsTeamProfile\n"
    ".type sceSystemServiceLaunchTournamentsTeamProfile @function\n"
    "sceSystemServiceLaunchTournamentsTeamProfile:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceLaunchTournamentsTeamProfile]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceLaunchWebBrowser;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceLaunchWebBrowser\n"
    ".type sceSystemServiceLaunchWebBrowser @function\n"
    "sceSystemServiceLaunchWebBrowser:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceLaunchWebBrowser]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceLoadExec;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceLoadExec\n"
    ".type sceSystemServiceLoadExec @function\n"
    "sceSystemServiceLoadExec:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceLoadExec]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceNavigateToAnotherApp;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceNavigateToAnotherApp\n"
    ".type sceSystemServiceNavigateToAnotherApp @function\n"
    "sceSystemServiceNavigateToAnotherApp:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceNavigateToAnotherApp]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceNavigateToGoBack;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceNavigateToGoBack\n"
    ".type sceSystemServiceNavigateToGoBack @function\n"
    "sceSystemServiceNavigateToGoBack:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceNavigateToGoBack]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceNavigateToGoBackWithValue;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceNavigateToGoBackWithValue\n"
    ".type sceSystemServiceNavigateToGoBackWithValue @function\n"
    "sceSystemServiceNavigateToGoBackWithValue:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceNavigateToGoBackWithValue]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceNavigateToGoHome;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceNavigateToGoHome\n"
    ".type sceSystemServiceNavigateToGoHome @function\n"
    "sceSystemServiceNavigateToGoHome:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceNavigateToGoHome]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceNotifyBgmCoreTermination;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceNotifyBgmCoreTermination\n"
    ".type sceSystemServiceNotifyBgmCoreTermination @function\n"
    "sceSystemServiceNotifyBgmCoreTermination:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceNotifyBgmCoreTermination]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceParamGetInt;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceParamGetInt\n"
    ".type sceSystemServiceParamGetInt @function\n"
    "sceSystemServiceParamGetInt:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceParamGetInt]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceParamGetString;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceParamGetString\n"
    ".type sceSystemServiceParamGetString @function\n"
    "sceSystemServiceParamGetString:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceParamGetString]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServicePowerTick;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServicePowerTick\n"
    ".type sceSystemServicePowerTick @function\n"
    "sceSystemServicePowerTick:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServicePowerTick]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceRaiseExceptionLocalProcess;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceRaiseExceptionLocalProcess\n"
    ".type sceSystemServiceRaiseExceptionLocalProcess @function\n"
    "sceSystemServiceRaiseExceptionLocalProcess:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceRaiseExceptionLocalProcess]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceReceiveEvent;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceReceiveEvent\n"
    ".type sceSystemServiceReceiveEvent @function\n"
    "sceSystemServiceReceiveEvent:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceReceiveEvent]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceReenableMediaPlay;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceReenableMediaPlay\n"
    ".type sceSystemServiceReenableMediaPlay @function\n"
    "sceSystemServiceReenableMediaPlay:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceReenableMediaPlay]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceReenableMusicPlayer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceReenableMusicPlayer\n"
    ".type sceSystemServiceReenableMusicPlayer @function\n"
    "sceSystemServiceReenableMusicPlayer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceReenableMusicPlayer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceRegisterDaemon;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceRegisterDaemon\n"
    ".type sceSystemServiceRegisterDaemon @function\n"
    "sceSystemServiceRegisterDaemon:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceRegisterDaemon]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceReleaseBgmCpuBudget;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceReleaseBgmCpuBudget\n"
    ".type sceSystemServiceReleaseBgmCpuBudget @function\n"
    "sceSystemServiceReleaseBgmCpuBudget:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceReleaseBgmCpuBudget]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceReleaseFb0;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceReleaseFb0\n"
    ".type sceSystemServiceReleaseFb0 @function\n"
    "sceSystemServiceReleaseFb0:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceReleaseFb0]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceReportAbnormalTermination;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceReportAbnormalTermination\n"
    ".type sceSystemServiceReportAbnormalTermination @function\n"
    "sceSystemServiceReportAbnormalTermination:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceReportAbnormalTermination]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceRequestCameraCalibration;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceRequestCameraCalibration\n"
    ".type sceSystemServiceRequestCameraCalibration @function\n"
    "sceSystemServiceRequestCameraCalibration:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceRequestCameraCalibration]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceRequestToChangeRenderingMode;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceRequestToChangeRenderingMode\n"
    ".type sceSystemServiceRequestToChangeRenderingMode @function\n"
    "sceSystemServiceRequestToChangeRenderingMode:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceRequestToChangeRenderingMode]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceResumeLocalProcess;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceResumeLocalProcess\n"
    ".type sceSystemServiceResumeLocalProcess @function\n"
    "sceSystemServiceResumeLocalProcess:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceResumeLocalProcess]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceSetControllerFocusPermission;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceSetControllerFocusPermission\n"
    ".type sceSystemServiceSetControllerFocusPermission @function\n"
    "sceSystemServiceSetControllerFocusPermission:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceSetControllerFocusPermission]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceSetGpuLoadEmulationMode;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceSetGpuLoadEmulationMode\n"
    ".type sceSystemServiceSetGpuLoadEmulationMode @function\n"
    "sceSystemServiceSetGpuLoadEmulationMode:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceSetGpuLoadEmulationMode]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceSetNoticeScreenSkipFlag;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceSetNoticeScreenSkipFlag\n"
    ".type sceSystemServiceSetNoticeScreenSkipFlag @function\n"
    "sceSystemServiceSetNoticeScreenSkipFlag:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceSetNoticeScreenSkipFlag]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceSetOutOfVrPlayAreaFlag;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceSetOutOfVrPlayAreaFlag\n"
    ".type sceSystemServiceSetOutOfVrPlayAreaFlag @function\n"
    "sceSystemServiceSetOutOfVrPlayAreaFlag:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceSetOutOfVrPlayAreaFlag]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceSetOutOfVrPlayZoneWarning;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceSetOutOfVrPlayZoneWarning\n"
    ".type sceSystemServiceSetOutOfVrPlayZoneWarning @function\n"
    "sceSystemServiceSetOutOfVrPlayZoneWarning:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceSetOutOfVrPlayZoneWarning]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceShowControllerSettings;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceShowControllerSettings\n"
    ".type sceSystemServiceShowControllerSettings @function\n"
    "sceSystemServiceShowControllerSettings:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceShowControllerSettings]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceShowDisplaySafeAreaSettings;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceShowDisplaySafeAreaSettings\n"
    ".type sceSystemServiceShowDisplaySafeAreaSettings @function\n"
    "sceSystemServiceShowDisplaySafeAreaSettings:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceShowDisplaySafeAreaSettings]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceShowErrorDialog;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceShowErrorDialog\n"
    ".type sceSystemServiceShowErrorDialog @function\n"
    "sceSystemServiceShowErrorDialog:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceShowErrorDialog]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceShowEyeToEyeDistanceSetting;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceShowEyeToEyeDistanceSetting\n"
    ".type sceSystemServiceShowEyeToEyeDistanceSetting @function\n"
    "sceSystemServiceShowEyeToEyeDistanceSetting:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceShowEyeToEyeDistanceSetting]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceSuspendBackgroundApp;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceSuspendBackgroundApp\n"
    ".type sceSystemServiceSuspendBackgroundApp @function\n"
    "sceSystemServiceSuspendBackgroundApp:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceSuspendBackgroundApp]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceSuspendLocalProcess;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceSuspendLocalProcess\n"
    ".type sceSystemServiceSuspendLocalProcess @function\n"
    "sceSystemServiceSuspendLocalProcess:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceSuspendLocalProcess]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceTickVideoPlayback;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceTickVideoPlayback\n"
    ".type sceSystemServiceTickVideoPlayback @function\n"
    "sceSystemServiceTickVideoPlayback:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceTickVideoPlayback]\n");

static __attribute__ ((used)) void* __ptr_sceSystemServiceTurnOffScreenSaver;
asm(".intel_syntax noprefix\n"
    ".global sceSystemServiceTurnOffScreenSaver\n"
    ".type sceSystemServiceTurnOffScreenSaver @function\n"
    "sceSystemServiceTurnOffScreenSaver:\n"
    "jmp qword ptr [rip + __ptr_sceSystemServiceTurnOffScreenSaver]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(103)))
__constructor(void) {
  if(sprx_dlopen("libSceSystemService", &__handle)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceAcquireBgmCpuBudget", &__ptr_sceSystemServiceAcquireBgmCpuBudget)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceAcquireFb0", &__ptr_sceSystemServiceAcquireFb0)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceAddLocalProcess", &__ptr_sceSystemServiceAddLocalProcess)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceAddLocalProcessForPsmKit", &__ptr_sceSystemServiceAddLocalProcessForPsmKit)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceAppGetAppInstallStatus", &__ptr_sceSystemServiceAppGetAppInstallStatus)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeAcpClock", &__ptr_sceSystemServiceChangeAcpClock)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeClock", &__ptr_sceSystemServiceChangeClock)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeCpuClock", &__ptr_sceSystemServiceChangeCpuClock)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeCpuPstate", &__ptr_sceSystemServiceChangeCpuPstate)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeGpuClock", &__ptr_sceSystemServiceChangeGpuClock)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeMemPstate", &__ptr_sceSystemServiceChangeMemPstate)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeMemoryClock", &__ptr_sceSystemServiceChangeMemoryClock)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeMemoryClockToBaseMode", &__ptr_sceSystemServiceChangeMemoryClockToBaseMode)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeMemoryClockToDefault", &__ptr_sceSystemServiceChangeMemoryClockToDefault)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeMemoryClockToMultiMediaMode", &__ptr_sceSystemServiceChangeMemoryClockToMultiMediaMode)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeNumberOfGpuCu", &__ptr_sceSystemServiceChangeNumberOfGpuCu)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeSamuClock", &__ptr_sceSystemServiceChangeSamuClock)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeUvdClock", &__ptr_sceSystemServiceChangeUvdClock)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceChangeVceClock", &__ptr_sceSystemServiceChangeVceClock)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceDisableMediaPlay", &__ptr_sceSystemServiceDisableMediaPlay)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceDisableMusicPlayer", &__ptr_sceSystemServiceDisableMusicPlayer)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceDisableNoticeScreenSkipFlagAutoSet", &__ptr_sceSystemServiceDisableNoticeScreenSkipFlagAutoSet)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceDisablePersonalEyeToEyeDistanceSetting", &__ptr_sceSystemServiceDisablePersonalEyeToEyeDistanceSetting)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceDisableSuspendConfirmationDialog", &__ptr_sceSystemServiceDisableSuspendConfirmationDialog)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceEnablePersonalEyeToEyeDistanceSetting", &__ptr_sceSystemServiceEnablePersonalEyeToEyeDistanceSetting)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceEnableSuspendConfirmationDialog", &__ptr_sceSystemServiceEnableSuspendConfirmationDialog)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetAppCategoryType", &__ptr_sceSystemServiceGetAppCategoryType)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetAppFocusedAppStatus", &__ptr_sceSystemServiceGetAppFocusedAppStatus)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetAppId", &__ptr_sceSystemServiceGetAppId)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetAppIdListOfBigApp", &__ptr_sceSystemServiceGetAppIdListOfBigApp)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetAppIdOfRunningBigApp", &__ptr_sceSystemServiceGetAppIdOfRunningBigApp)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetAppLaunchedUser", &__ptr_sceSystemServiceGetAppLaunchedUser)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetAppStatus", &__ptr_sceSystemServiceGetAppStatus)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetAppTitleId", &__ptr_sceSystemServiceGetAppTitleId)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetAppType", &__ptr_sceSystemServiceGetAppType)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetDisplaySafeAreaInfo", &__ptr_sceSystemServiceGetDisplaySafeAreaInfo)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetEventForDaemon", &__ptr_sceSystemServiceGetEventForDaemon)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetGpuLoadEmulationMode", &__ptr_sceSystemServiceGetGpuLoadEmulationMode)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetHdrToneMapLuminance", &__ptr_sceSystemServiceGetHdrToneMapLuminance)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetLocalProcessStatusList", &__ptr_sceSystemServiceGetLocalProcessStatusList)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetMainAppTitleId", &__ptr_sceSystemServiceGetMainAppTitleId)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetNoticeScreenSkipFlag", &__ptr_sceSystemServiceGetNoticeScreenSkipFlag)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetPSButtonEvent", &__ptr_sceSystemServiceGetPSButtonEvent)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetParentSocket", &__ptr_sceSystemServiceGetParentSocket)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetParentSocketForPsmKit", &__ptr_sceSystemServiceGetParentSocketForPsmKit)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetRemoteplayStatus", &__ptr_sceSystemServiceGetRemoteplayStatus)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetRenderingMode", &__ptr_sceSystemServiceGetRenderingMode)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetStatus", &__ptr_sceSystemServiceGetStatus)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetSubAppTitleId", &__ptr_sceSystemServiceGetSubAppTitleId)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetSubAppTitleIdForSP", &__ptr_sceSystemServiceGetSubAppTitleIdForSP)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetTitleWorkaroundInfo", &__ptr_sceSystemServiceGetTitleWorkaroundInfo)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetUIStatus", &__ptr_sceSystemServiceGetUIStatus)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceGetVersionNumberOfCameraCalibrationData", &__ptr_sceSystemServiceGetVersionNumberOfCameraCalibrationData)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceHideSplashScreen", &__ptr_sceSystemServiceHideSplashScreen)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceInitializePlayerDialogParam", &__ptr_sceSystemServiceInitializePlayerDialogParam)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceIsAppSuspended", &__ptr_sceSystemServiceIsAppSuspended)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceIsBgmCpuBudgetAvailable", &__ptr_sceSystemServiceIsBgmCpuBudgetAvailable)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceIsBgmPlaying", &__ptr_sceSystemServiceIsBgmPlaying)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceIsEyeToEyeDistanceAdjusted", &__ptr_sceSystemServiceIsEyeToEyeDistanceAdjusted)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceIsGameLiveStreamingOnAir", &__ptr_sceSystemServiceIsGameLiveStreamingOnAir)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceIsScreenSaverOn", &__ptr_sceSystemServiceIsScreenSaverOn)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceIsShellUiFgAndGameBgCpuMode", &__ptr_sceSystemServiceIsShellUiFgAndGameBgCpuMode)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceKillApp", &__ptr_sceSystemServiceKillApp)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceKillLocalProcess", &__ptr_sceSystemServiceKillLocalProcess)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceKillLocalProcessForPsmKit", &__ptr_sceSystemServiceKillLocalProcessForPsmKit)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceLaunchApp", &__ptr_sceSystemServiceLaunchApp)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceLaunchEventDetails", &__ptr_sceSystemServiceLaunchEventDetails)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceLaunchPlayerDialog", &__ptr_sceSystemServiceLaunchPlayerDialog)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceLaunchTournamentList", &__ptr_sceSystemServiceLaunchTournamentList)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceLaunchTournamentsTeamProfile", &__ptr_sceSystemServiceLaunchTournamentsTeamProfile)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceLaunchWebBrowser", &__ptr_sceSystemServiceLaunchWebBrowser)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceLoadExec", &__ptr_sceSystemServiceLoadExec)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceNavigateToAnotherApp", &__ptr_sceSystemServiceNavigateToAnotherApp)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceNavigateToGoBack", &__ptr_sceSystemServiceNavigateToGoBack)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceNavigateToGoBackWithValue", &__ptr_sceSystemServiceNavigateToGoBackWithValue)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceNavigateToGoHome", &__ptr_sceSystemServiceNavigateToGoHome)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceNotifyBgmCoreTermination", &__ptr_sceSystemServiceNotifyBgmCoreTermination)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceParamGetInt", &__ptr_sceSystemServiceParamGetInt)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceParamGetString", &__ptr_sceSystemServiceParamGetString)) return;
  if(sprx_dlsym(__handle, "sceSystemServicePowerTick", &__ptr_sceSystemServicePowerTick)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceRaiseExceptionLocalProcess", &__ptr_sceSystemServiceRaiseExceptionLocalProcess)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceReceiveEvent", &__ptr_sceSystemServiceReceiveEvent)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceReenableMediaPlay", &__ptr_sceSystemServiceReenableMediaPlay)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceReenableMusicPlayer", &__ptr_sceSystemServiceReenableMusicPlayer)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceRegisterDaemon", &__ptr_sceSystemServiceRegisterDaemon)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceReleaseBgmCpuBudget", &__ptr_sceSystemServiceReleaseBgmCpuBudget)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceReleaseFb0", &__ptr_sceSystemServiceReleaseFb0)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceReportAbnormalTermination", &__ptr_sceSystemServiceReportAbnormalTermination)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceRequestCameraCalibration", &__ptr_sceSystemServiceRequestCameraCalibration)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceRequestToChangeRenderingMode", &__ptr_sceSystemServiceRequestToChangeRenderingMode)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceResumeLocalProcess", &__ptr_sceSystemServiceResumeLocalProcess)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceSetControllerFocusPermission", &__ptr_sceSystemServiceSetControllerFocusPermission)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceSetGpuLoadEmulationMode", &__ptr_sceSystemServiceSetGpuLoadEmulationMode)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceSetNoticeScreenSkipFlag", &__ptr_sceSystemServiceSetNoticeScreenSkipFlag)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceSetOutOfVrPlayAreaFlag", &__ptr_sceSystemServiceSetOutOfVrPlayAreaFlag)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceSetOutOfVrPlayZoneWarning", &__ptr_sceSystemServiceSetOutOfVrPlayZoneWarning)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceShowControllerSettings", &__ptr_sceSystemServiceShowControllerSettings)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceShowDisplaySafeAreaSettings", &__ptr_sceSystemServiceShowDisplaySafeAreaSettings)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceShowErrorDialog", &__ptr_sceSystemServiceShowErrorDialog)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceShowEyeToEyeDistanceSetting", &__ptr_sceSystemServiceShowEyeToEyeDistanceSetting)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceSuspendBackgroundApp", &__ptr_sceSystemServiceSuspendBackgroundApp)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceSuspendLocalProcess", &__ptr_sceSystemServiceSuspendLocalProcess)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceTickVideoPlayback", &__ptr_sceSystemServiceTickVideoPlayback)) return;
  if(sprx_dlsym(__handle, "sceSystemServiceTurnOffScreenSaver", &__ptr_sceSystemServiceTurnOffScreenSaver)) return;
}

static void __attribute__((destructor(103)))
__destructor(void) {
  sprx_dlclose(__handle);
}
