/*
 This file was generated by trampgen.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);

static __attribute__ ((used)) void* __ptr_sceRandomGetRandomNumber;
asm(".intel_syntax noprefix\n"
    ".global sceRandomGetRandomNumber\n"
    ".type sceRandomGetRandomNumber @function\n"
    "sceRandomGetRandomNumber:\n"
    "jmp qword ptr [rip + __ptr_sceRandomGetRandomNumber]\n");

static unsigned short __handle = 0x2001;
static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceRandom", &__handle);
  sprx_dlsym(__handle, "sceRandomGetRandomNumber", &__ptr_sceRandomGetRandomNumber);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}
