/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceDbgVideoOutAddOutputModeVr60Privilege;
asm(".intel_syntax noprefix\n"
    ".global sceDbgVideoOutAddOutputModeVr60Privilege\n"
    ".type sceDbgVideoOutAddOutputModeVr60Privilege @function\n"
    "sceDbgVideoOutAddOutputModeVr60Privilege:\n"
    "jmp qword ptr [rip + __ptr_sceDbgVideoOutAddOutputModeVr60Privilege]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddBuffer\n"
    ".type sceVideoOutAddBuffer @function\n"
    "sceVideoOutAddBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddBuffer4k2kPrivilege;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddBuffer4k2kPrivilege\n"
    ".type sceVideoOutAddBuffer4k2kPrivilege @function\n"
    "sceVideoOutAddBuffer4k2kPrivilege:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddBuffer4k2kPrivilege]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddBufferAnisoPrivilege;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddBufferAnisoPrivilege\n"
    ".type sceVideoOutAddBufferAnisoPrivilege @function\n"
    "sceVideoOutAddBufferAnisoPrivilege:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddBufferAnisoPrivilege]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddBufferAttributeOption;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddBufferAttributeOption\n"
    ".type sceVideoOutAddBufferAttributeOption @function\n"
    "sceVideoOutAddBufferAttributeOption:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddBufferAttributeOption]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddBufferHdrPrivilege;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddBufferHdrPrivilege\n"
    ".type sceVideoOutAddBufferHdrPrivilege @function\n"
    "sceVideoOutAddBufferHdrPrivilege:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddBufferHdrPrivilege]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddBufferYccPrivilege;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddBufferYccPrivilege\n"
    ".type sceVideoOutAddBufferYccPrivilege @function\n"
    "sceVideoOutAddBufferYccPrivilege:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddBufferYccPrivilege]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddDisplayPositionEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddDisplayPositionEvent\n"
    ".type sceVideoOutAddDisplayPositionEvent @function\n"
    "sceVideoOutAddDisplayPositionEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddDisplayPositionEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddDriver;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddDriver\n"
    ".type sceVideoOutAddDriver @function\n"
    "sceVideoOutAddDriver:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddDriver]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddFlipEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddFlipEvent\n"
    ".type sceVideoOutAddFlipEvent @function\n"
    "sceVideoOutAddFlipEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddFlipEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddOutputModeEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddOutputModeEvent\n"
    ".type sceVideoOutAddOutputModeEvent @function\n"
    "sceVideoOutAddOutputModeEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddOutputModeEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddPreVblankStartEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddPreVblankStartEvent\n"
    ".type sceVideoOutAddPreVblankStartEvent @function\n"
    "sceVideoOutAddPreVblankStartEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddPreVblankStartEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddS3dHmdPrivilege;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddS3dHmdPrivilege\n"
    ".type sceVideoOutAddS3dHmdPrivilege @function\n"
    "sceVideoOutAddS3dHmdPrivilege:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddS3dHmdPrivilege]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddSetModeEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddSetModeEvent\n"
    ".type sceVideoOutAddSetModeEvent @function\n"
    "sceVideoOutAddSetModeEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddSetModeEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddStereoBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddStereoBuffer\n"
    ".type sceVideoOutAddStereoBuffer @function\n"
    "sceVideoOutAddStereoBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddStereoBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAddVblankEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAddVblankEvent\n"
    ".type sceVideoOutAddVblankEvent @function\n"
    "sceVideoOutAddVblankEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAddVblankEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAdjustColor2_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAdjustColor2_\n"
    ".type sceVideoOutAdjustColor2_ @function\n"
    "sceVideoOutAdjustColor2_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAdjustColor2_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAdjustColorSpaceConversion_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAdjustColorSpaceConversion_\n"
    ".type sceVideoOutAdjustColorSpaceConversion_ @function\n"
    "sceVideoOutAdjustColorSpaceConversion_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAdjustColorSpaceConversion_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutAdjustColor_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutAdjustColor_\n"
    ".type sceVideoOutAdjustColor_ @function\n"
    "sceVideoOutAdjustColor_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutAdjustColor_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutClearFlipMaster;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutClearFlipMaster\n"
    ".type sceVideoOutClearFlipMaster @function\n"
    "sceVideoOutClearFlipMaster:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutClearFlipMaster]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutClose;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutClose\n"
    ".type sceVideoOutClose @function\n"
    "sceVideoOutClose:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutClose]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutColorSettingsSetGamma_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutColorSettingsSetGamma_\n"
    ".type sceVideoOutColorSettingsSetGamma_ @function\n"
    "sceVideoOutColorSettingsSetGamma_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutColorSettingsSetGamma_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutColorSpaceConversionSettingsSetDefaultSdrToHdrConversion_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutColorSpaceConversionSettingsSetDefaultSdrToHdrConversion_\n"
    ".type sceVideoOutColorSpaceConversionSettingsSetDefaultSdrToHdrConversion_ @function\n"
    "sceVideoOutColorSpaceConversionSettingsSetDefaultSdrToHdrConversion_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutColorSpaceConversionSettingsSetDefaultSdrToHdrConversion_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutColorSpaceConversionSettingsSetSdrToHdrConversion_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutColorSpaceConversionSettingsSetSdrToHdrConversion_\n"
    ".type sceVideoOutColorSpaceConversionSettingsSetSdrToHdrConversion_ @function\n"
    "sceVideoOutColorSpaceConversionSettingsSetSdrToHdrConversion_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutColorSpaceConversionSettingsSetSdrToHdrConversion_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutConfigureLayout;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutConfigureLayout\n"
    ".type sceVideoOutConfigureLayout @function\n"
    "sceVideoOutConfigureLayout:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutConfigureLayout]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutConfigureOptionsInitialize_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutConfigureOptionsInitialize_\n"
    ".type sceVideoOutConfigureOptionsInitialize_ @function\n"
    "sceVideoOutConfigureOptionsInitialize_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutConfigureOptionsInitialize_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutConfigureOutput;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutConfigureOutput\n"
    ".type sceVideoOutConfigureOutput @function\n"
    "sceVideoOutConfigureOutput:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutConfigureOutput]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutConfigureOutputEx;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutConfigureOutputEx\n"
    ".type sceVideoOutConfigureOutputEx @function\n"
    "sceVideoOutConfigureOutputEx:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutConfigureOutputEx]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutConfigureOutputModeExSubmitDoneUnsafe_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutConfigureOutputModeExSubmitDoneUnsafe_\n"
    ".type sceVideoOutConfigureOutputModeExSubmitDoneUnsafe_ @function\n"
    "sceVideoOutConfigureOutputModeExSubmitDoneUnsafe_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutConfigureOutputModeExSubmitDoneUnsafe_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutConfigureOutputModeEx_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutConfigureOutputModeEx_\n"
    ".type sceVideoOutConfigureOutputModeEx_ @function\n"
    "sceVideoOutConfigureOutputModeEx_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutConfigureOutputModeEx_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutConfigureOutputMode_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutConfigureOutputMode_\n"
    ".type sceVideoOutConfigureOutputMode_ @function\n"
    "sceVideoOutConfigureOutputMode_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutConfigureOutputMode_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutControlHdcpEncryption;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutControlHdcpEncryption\n"
    ".type sceVideoOutControlHdcpEncryption @function\n"
    "sceVideoOutControlHdcpEncryption:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutControlHdcpEncryption]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutCursorDisable;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutCursorDisable\n"
    ".type sceVideoOutCursorDisable @function\n"
    "sceVideoOutCursorDisable:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutCursorDisable]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutCursorEnable;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutCursorEnable\n"
    ".type sceVideoOutCursorEnable @function\n"
    "sceVideoOutCursorEnable:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutCursorEnable]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutCursorIsUpdatePending;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutCursorIsUpdatePending\n"
    ".type sceVideoOutCursorIsUpdatePending @function\n"
    "sceVideoOutCursorIsUpdatePending:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutCursorIsUpdatePending]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutCursorSet2xMagnify;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutCursorSet2xMagnify\n"
    ".type sceVideoOutCursorSet2xMagnify @function\n"
    "sceVideoOutCursorSet2xMagnify:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutCursorSet2xMagnify]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutCursorSetHotSpot;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutCursorSetHotSpot\n"
    ".type sceVideoOutCursorSetHotSpot @function\n"
    "sceVideoOutCursorSetHotSpot:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutCursorSetHotSpot]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutCursorSetImageAddress;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutCursorSetImageAddress\n"
    ".type sceVideoOutCursorSetImageAddress @function\n"
    "sceVideoOutCursorSetImageAddress:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutCursorSetImageAddress]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutCursorSetPosition;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutCursorSetPosition\n"
    ".type sceVideoOutCursorSetPosition @function\n"
    "sceVideoOutCursorSetPosition:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutCursorSetPosition]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutCursorSetPositionStereo;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutCursorSetPositionStereo\n"
    ".type sceVideoOutCursorSetPositionStereo @function\n"
    "sceVideoOutCursorSetPositionStereo:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutCursorSetPositionStereo]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutCurveSamplePointsCalc_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutCurveSamplePointsCalc_\n"
    ".type sceVideoOutCurveSamplePointsCalc_ @function\n"
    "sceVideoOutCurveSamplePointsCalc_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutCurveSamplePointsCalc_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDeleteDisplayPositionEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDeleteDisplayPositionEvent\n"
    ".type sceVideoOutDeleteDisplayPositionEvent @function\n"
    "sceVideoOutDeleteDisplayPositionEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDeleteDisplayPositionEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDeleteDriver;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDeleteDriver\n"
    ".type sceVideoOutDeleteDriver @function\n"
    "sceVideoOutDeleteDriver:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDeleteDriver]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDeleteFlipEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDeleteFlipEvent\n"
    ".type sceVideoOutDeleteFlipEvent @function\n"
    "sceVideoOutDeleteFlipEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDeleteFlipEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDeletePreVblankStartEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDeletePreVblankStartEvent\n"
    ".type sceVideoOutDeletePreVblankStartEvent @function\n"
    "sceVideoOutDeletePreVblankStartEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDeletePreVblankStartEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDeleteSetModeEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDeleteSetModeEvent\n"
    ".type sceVideoOutDeleteSetModeEvent @function\n"
    "sceVideoOutDeleteSetModeEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDeleteSetModeEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDeleteVblankEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDeleteVblankEvent\n"
    ".type sceVideoOutDeleteVblankEvent @function\n"
    "sceVideoOutDeleteVblankEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDeleteVblankEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDriverAddEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDriverAddEvent\n"
    ".type sceVideoOutDriverAddEvent @function\n"
    "sceVideoOutDriverAddEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDriverAddEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDriverDecrementBufferLabel;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDriverDecrementBufferLabel\n"
    ".type sceVideoOutDriverDecrementBufferLabel @function\n"
    "sceVideoOutDriverDecrementBufferLabel:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDriverDecrementBufferLabel]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDriverDeleteEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDriverDeleteEvent\n"
    ".type sceVideoOutDriverDeleteEvent @function\n"
    "sceVideoOutDriverDeleteEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDriverDeleteEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDriverGetBufferLabelAddress;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDriverGetBufferLabelAddress\n"
    ".type sceVideoOutDriverGetBufferLabelAddress @function\n"
    "sceVideoOutDriverGetBufferLabelAddress:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDriverGetBufferLabelAddress]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDriverGetEopHandle;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDriverGetEopHandle\n"
    ".type sceVideoOutDriverGetEopHandle @function\n"
    "sceVideoOutDriverGetEopHandle:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDriverGetEopHandle]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDriverGetFinishedEopHandle;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDriverGetFinishedEopHandle\n"
    ".type sceVideoOutDriverGetFinishedEopHandle @function\n"
    "sceVideoOutDriverGetFinishedEopHandle:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDriverGetFinishedEopHandle]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDriverGetLatestEopHandle;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDriverGetLatestEopHandle\n"
    ".type sceVideoOutDriverGetLatestEopHandle @function\n"
    "sceVideoOutDriverGetLatestEopHandle:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDriverGetLatestEopHandle]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDriverIncrementBufferLabel;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDriverIncrementBufferLabel\n"
    ".type sceVideoOutDriverIncrementBufferLabel @function\n"
    "sceVideoOutDriverIncrementBufferLabel:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDriverIncrementBufferLabel]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDriverResetBufferLabel;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDriverResetBufferLabel\n"
    ".type sceVideoOutDriverResetBufferLabel @function\n"
    "sceVideoOutDriverResetBufferLabel:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDriverResetBufferLabel]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutDriverTriggerEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutDriverTriggerEvent\n"
    ".type sceVideoOutDriverTriggerEvent @function\n"
    "sceVideoOutDriverTriggerEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutDriverTriggerEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetBufferInformation;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetBufferInformation\n"
    ".type sceVideoOutGetBufferInformation @function\n"
    "sceVideoOutGetBufferInformation:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetBufferInformation]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetBufferLabelAddress;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetBufferLabelAddress\n"
    ".type sceVideoOutGetBufferLabelAddress @function\n"
    "sceVideoOutGetBufferLabelAddress:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetBufferLabelAddress]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetCoredumpOutputMode;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetCoredumpOutputMode\n"
    ".type sceVideoOutGetCoredumpOutputMode @function\n"
    "sceVideoOutGetCoredumpOutputMode:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetCoredumpOutputMode]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetCurrentOutputMode_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetCurrentOutputMode_\n"
    ".type sceVideoOutGetCurrentOutputMode_ @function\n"
    "sceVideoOutGetCurrentOutputMode_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetCurrentOutputMode_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetDeviceCapabilityInfo_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetDeviceCapabilityInfo_\n"
    ".type sceVideoOutGetDeviceCapabilityInfo_ @function\n"
    "sceVideoOutGetDeviceCapabilityInfo_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetDeviceCapabilityInfo_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetDeviceInfoExOts_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetDeviceInfoExOts_\n"
    ".type sceVideoOutGetDeviceInfoExOts_ @function\n"
    "sceVideoOutGetDeviceInfoExOts_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetDeviceInfoExOts_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetDeviceInfoEx_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetDeviceInfoEx_\n"
    ".type sceVideoOutGetDeviceInfoEx_ @function\n"
    "sceVideoOutGetDeviceInfoEx_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetDeviceInfoEx_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetEventCount;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetEventCount\n"
    ".type sceVideoOutGetEventCount @function\n"
    "sceVideoOutGetEventCount:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetEventCount]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetEventData;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetEventData\n"
    ".type sceVideoOutGetEventData @function\n"
    "sceVideoOutGetEventData:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetEventData]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetEventId;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetEventId\n"
    ".type sceVideoOutGetEventId @function\n"
    "sceVideoOutGetEventId:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetEventId]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetFlipStatus;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetFlipStatus\n"
    ".type sceVideoOutGetFlipStatus @function\n"
    "sceVideoOutGetFlipStatus:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetFlipStatus]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetHdmiKsvList_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetHdmiKsvList_\n"
    ".type sceVideoOutGetHdmiKsvList_ @function\n"
    "sceVideoOutGetHdmiKsvList_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetHdmiKsvList_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetHdmiMonitorInfoNoMask_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetHdmiMonitorInfoNoMask_\n"
    ".type sceVideoOutGetHdmiMonitorInfoNoMask_ @function\n"
    "sceVideoOutGetHdmiMonitorInfoNoMask_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetHdmiMonitorInfoNoMask_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetHdmiMonitorInfo_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetHdmiMonitorInfo_\n"
    ".type sceVideoOutGetHdmiMonitorInfo_ @function\n"
    "sceVideoOutGetHdmiMonitorInfo_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetHdmiMonitorInfo_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetHdmiRawEdid_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetHdmiRawEdid_\n"
    ".type sceVideoOutGetHdmiRawEdid_ @function\n"
    "sceVideoOutGetHdmiRawEdid_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetHdmiRawEdid_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetMonitorInfo;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetMonitorInfo\n"
    ".type sceVideoOutGetMonitorInfo @function\n"
    "sceVideoOutGetMonitorInfo:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetMonitorInfo]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetOutputStatus;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetOutputStatus\n"
    ".type sceVideoOutGetOutputStatus @function\n"
    "sceVideoOutGetOutputStatus:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetOutputStatus]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetPortStatusInfo;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetPortStatusInfo\n"
    ".type sceVideoOutGetPortStatusInfo @function\n"
    "sceVideoOutGetPortStatusInfo:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetPortStatusInfo]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetPortStatusInfoByBusSpecifier_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetPortStatusInfoByBusSpecifier_\n"
    ".type sceVideoOutGetPortStatusInfoByBusSpecifier_ @function\n"
    "sceVideoOutGetPortStatusInfoByBusSpecifier_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetPortStatusInfoByBusSpecifier_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetPortStatusInfo_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetPortStatusInfo_\n"
    ".type sceVideoOutGetPortStatusInfo_ @function\n"
    "sceVideoOutGetPortStatusInfo_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetPortStatusInfo_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetResolutionStatus;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetResolutionStatus\n"
    ".type sceVideoOutGetResolutionStatus @function\n"
    "sceVideoOutGetResolutionStatus:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetResolutionStatus]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetStatusForWebcore;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetStatusForWebcore\n"
    ".type sceVideoOutGetStatusForWebcore @function\n"
    "sceVideoOutGetStatusForWebcore:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetStatusForWebcore]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetVblankStatus;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetVblankStatus\n"
    ".type sceVideoOutGetVblankStatus @function\n"
    "sceVideoOutGetVblankStatus:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetVblankStatus]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutGetVideoOutModeByBusSpecifier_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutGetVideoOutModeByBusSpecifier_\n"
    ".type sceVideoOutGetVideoOutModeByBusSpecifier_ @function\n"
    "sceVideoOutGetVideoOutModeByBusSpecifier_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutGetVideoOutModeByBusSpecifier_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutHdmiMonitorInfoIsSupportedHdcpVersion;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutHdmiMonitorInfoIsSupportedHdcpVersion\n"
    ".type sceVideoOutHdmiMonitorInfoIsSupportedHdcpVersion @function\n"
    "sceVideoOutHdmiMonitorInfoIsSupportedHdcpVersion:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutHdmiMonitorInfoIsSupportedHdcpVersion]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutHdmiMonitorInfoIsSupportedVideoOutMode_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutHdmiMonitorInfoIsSupportedVideoOutMode_\n"
    ".type sceVideoOutHdmiMonitorInfoIsSupportedVideoOutMode_ @function\n"
    "sceVideoOutHdmiMonitorInfoIsSupportedVideoOutMode_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutHdmiMonitorInfoIsSupportedVideoOutMode_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutInitializeOutputOptions;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutInitializeOutputOptions\n"
    ".type sceVideoOutInitializeOutputOptions @function\n"
    "sceVideoOutInitializeOutputOptions:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutInitializeOutputOptions]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutIsFlipPending;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutIsFlipPending\n"
    ".type sceVideoOutIsFlipPending @function\n"
    "sceVideoOutIsFlipPending:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutIsFlipPending]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutIsOutputSupported;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutIsOutputSupported\n"
    ".type sceVideoOutIsOutputSupported @function\n"
    "sceVideoOutIsOutputSupported:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutIsOutputSupported]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutLockBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutLockBuffer\n"
    ".type sceVideoOutLockBuffer @function\n"
    "sceVideoOutLockBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutLockBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutModeSetAny_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutModeSetAny_\n"
    ".type sceVideoOutModeSetAny_ @function\n"
    "sceVideoOutModeSetAny_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutModeSetAny_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutOpen;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutOpen\n"
    ".type sceVideoOutOpen @function\n"
    "sceVideoOutOpen:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutOpen]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutRazorAddCallback;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutRazorAddCallback\n"
    ".type sceVideoOutRazorAddCallback @function\n"
    "sceVideoOutRazorAddCallback:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutRazorAddCallback]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutRazorRecallCallbacks;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutRazorRecallCallbacks\n"
    ".type sceVideoOutRazorRecallCallbacks @function\n"
    "sceVideoOutRazorRecallCallbacks:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutRazorRecallCallbacks]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutRazorRemoveCallback;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutRazorRemoveCallback\n"
    ".type sceVideoOutRazorRemoveCallback @function\n"
    "sceVideoOutRazorRemoveCallback:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutRazorRemoveCallback]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutRegisterBufferAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutRegisterBufferAttribute\n"
    ".type sceVideoOutRegisterBufferAttribute @function\n"
    "sceVideoOutRegisterBufferAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutRegisterBufferAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutRegisterBuffers;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutRegisterBuffers\n"
    ".type sceVideoOutRegisterBuffers @function\n"
    "sceVideoOutRegisterBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutRegisterBuffers]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutRegisterBuffers2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutRegisterBuffers2\n"
    ".type sceVideoOutRegisterBuffers2 @function\n"
    "sceVideoOutRegisterBuffers2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutRegisterBuffers2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutRegisterStereoBuffers;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutRegisterStereoBuffers\n"
    ".type sceVideoOutRegisterStereoBuffers @function\n"
    "sceVideoOutRegisterStereoBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutRegisterStereoBuffers]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutRemoveBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutRemoveBuffer\n"
    ".type sceVideoOutRemoveBuffer @function\n"
    "sceVideoOutRemoveBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutRemoveBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutRemoveBufferAttributeOption;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutRemoveBufferAttributeOption\n"
    ".type sceVideoOutRemoveBufferAttributeOption @function\n"
    "sceVideoOutRemoveBufferAttributeOption:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutRemoveBufferAttributeOption]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetAlphaControl;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetAlphaControl\n"
    ".type sceVideoOutSetAlphaControl @function\n"
    "sceVideoOutSetAlphaControl:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetAlphaControl]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetBlankAfterResume;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetBlankAfterResume\n"
    ".type sceVideoOutSetBlankAfterResume @function\n"
    "sceVideoOutSetBlankAfterResume:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetBlankAfterResume]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetBufferAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetBufferAttribute\n"
    ".type sceVideoOutSetBufferAttribute @function\n"
    "sceVideoOutSetBufferAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetBufferAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetBufferAttribute2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetBufferAttribute2\n"
    ".type sceVideoOutSetBufferAttribute2 @function\n"
    "sceVideoOutSetBufferAttribute2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetBufferAttribute2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetContentType;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetContentType\n"
    ".type sceVideoOutSetContentType @function\n"
    "sceVideoOutSetContentType:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetContentType]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetDisplayEventPosition;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetDisplayEventPosition\n"
    ".type sceVideoOutSetDisplayEventPosition @function\n"
    "sceVideoOutSetDisplayEventPosition:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetDisplayEventPosition]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetFlipMaster;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetFlipMaster\n"
    ".type sceVideoOutSetFlipMaster @function\n"
    "sceVideoOutSetFlipMaster:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetFlipMaster]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetFlipRate;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetFlipRate\n"
    ".type sceVideoOutSetFlipRate @function\n"
    "sceVideoOutSetFlipRate:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetFlipRate]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetGamutMetadata_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetGamutMetadata_\n"
    ".type sceVideoOutSetGamutMetadata_ @function\n"
    "sceVideoOutSetGamutMetadata_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetGamutMetadata_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetGlobalBlendSpace;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetGlobalBlendSpace\n"
    ".type sceVideoOutSetGlobalBlendSpace @function\n"
    "sceVideoOutSetGlobalBlendSpace:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetGlobalBlendSpace]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetToneMap_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetToneMap_\n"
    ".type sceVideoOutSetToneMap_ @function\n"
    "sceVideoOutSetToneMap_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetToneMap_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSetWindowModeMargins;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSetWindowModeMargins\n"
    ".type sceVideoOutSetWindowModeMargins @function\n"
    "sceVideoOutSetWindowModeMargins:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSetWindowModeMargins]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSubmitChangeBufferAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSubmitChangeBufferAttribute\n"
    ".type sceVideoOutSubmitChangeBufferAttribute @function\n"
    "sceVideoOutSubmitChangeBufferAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSubmitChangeBufferAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSubmitChangeBufferAttribute2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSubmitChangeBufferAttribute2\n"
    ".type sceVideoOutSubmitChangeBufferAttribute2 @function\n"
    "sceVideoOutSubmitChangeBufferAttribute2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSubmitChangeBufferAttribute2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSubmitEopFlip;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSubmitEopFlip\n"
    ".type sceVideoOutSubmitEopFlip @function\n"
    "sceVideoOutSubmitEopFlip:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSubmitEopFlip]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSubmitFlip;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSubmitFlip\n"
    ".type sceVideoOutSubmitFlip @function\n"
    "sceVideoOutSubmitFlip:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSubmitFlip]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysAddSetModeEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysAddSetModeEvent\n"
    ".type sceVideoOutSysAddSetModeEvent @function\n"
    "sceVideoOutSysAddSetModeEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysAddSetModeEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysAddSetModeEvent2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysAddSetModeEvent2\n"
    ".type sceVideoOutSysAddSetModeEvent2 @function\n"
    "sceVideoOutSysAddSetModeEvent2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysAddSetModeEvent2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysAddVblankEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysAddVblankEvent\n"
    ".type sceVideoOutSysAddVblankEvent @function\n"
    "sceVideoOutSysAddVblankEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysAddVblankEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysAddVblankEvent2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysAddVblankEvent2\n"
    ".type sceVideoOutSysAddVblankEvent2 @function\n"
    "sceVideoOutSysAddVblankEvent2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysAddVblankEvent2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysClose;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysClose\n"
    ".type sceVideoOutSysClose @function\n"
    "sceVideoOutSysClose:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysClose]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysConfigureLayout;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysConfigureLayout\n"
    ".type sceVideoOutSysConfigureLayout @function\n"
    "sceVideoOutSysConfigureLayout:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysConfigureLayout]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysConfigureOutput;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysConfigureOutput\n"
    ".type sceVideoOutSysConfigureOutput @function\n"
    "sceVideoOutSysConfigureOutput:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysConfigureOutput]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysConfigureOutputMode;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysConfigureOutputMode\n"
    ".type sceVideoOutSysConfigureOutputMode @function\n"
    "sceVideoOutSysConfigureOutputMode:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysConfigureOutputMode]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysCursorDisable;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysCursorDisable\n"
    ".type sceVideoOutSysCursorDisable @function\n"
    "sceVideoOutSysCursorDisable:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysCursorDisable]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysCursorEnable;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysCursorEnable\n"
    ".type sceVideoOutSysCursorEnable @function\n"
    "sceVideoOutSysCursorEnable:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysCursorEnable]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysCursorIsUpdatePending;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysCursorIsUpdatePending\n"
    ".type sceVideoOutSysCursorIsUpdatePending @function\n"
    "sceVideoOutSysCursorIsUpdatePending:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysCursorIsUpdatePending]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysCursorObtain;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysCursorObtain\n"
    ".type sceVideoOutSysCursorObtain @function\n"
    "sceVideoOutSysCursorObtain:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysCursorObtain]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysCursorRelease;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysCursorRelease\n"
    ".type sceVideoOutSysCursorRelease @function\n"
    "sceVideoOutSysCursorRelease:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysCursorRelease]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysCursorSetPosition;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysCursorSetPosition\n"
    ".type sceVideoOutSysCursorSetPosition @function\n"
    "sceVideoOutSysCursorSetPosition:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysCursorSetPosition]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysDeleteVblankEvent;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysDeleteVblankEvent\n"
    ".type sceVideoOutSysDeleteVblankEvent @function\n"
    "sceVideoOutSysDeleteVblankEvent:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysDeleteVblankEvent]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysDeleteVblankEvent2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysDeleteVblankEvent2\n"
    ".type sceVideoOutSysDeleteVblankEvent2 @function\n"
    "sceVideoOutSysDeleteVblankEvent2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysDeleteVblankEvent2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysGetBus;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysGetBus\n"
    ".type sceVideoOutSysGetBus @function\n"
    "sceVideoOutSysGetBus:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysGetBus]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysGetColorConversionStatus;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysGetColorConversionStatus\n"
    ".type sceVideoOutSysGetColorConversionStatus @function\n"
    "sceVideoOutSysGetColorConversionStatus:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysGetColorConversionStatus]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysGetCurrentOutputMode;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysGetCurrentOutputMode\n"
    ".type sceVideoOutSysGetCurrentOutputMode @function\n"
    "sceVideoOutSysGetCurrentOutputMode:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysGetCurrentOutputMode]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysGetDeviceInfo;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysGetDeviceInfo\n"
    ".type sceVideoOutSysGetDeviceInfo @function\n"
    "sceVideoOutSysGetDeviceInfo:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysGetDeviceInfo]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysGetFlipStatus;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysGetFlipStatus\n"
    ".type sceVideoOutSysGetFlipStatus @function\n"
    "sceVideoOutSysGetFlipStatus:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysGetFlipStatus]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysGetMonitorInfo_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysGetMonitorInfo_\n"
    ".type sceVideoOutSysGetMonitorInfo_ @function\n"
    "sceVideoOutSysGetMonitorInfo_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysGetMonitorInfo_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysGetResolutionStatus;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysGetResolutionStatus\n"
    ".type sceVideoOutSysGetResolutionStatus @function\n"
    "sceVideoOutSysGetResolutionStatus:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysGetResolutionStatus]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysGetResolutionStatus2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysGetResolutionStatus2\n"
    ".type sceVideoOutSysGetResolutionStatus2 @function\n"
    "sceVideoOutSysGetResolutionStatus2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysGetResolutionStatus2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysGetVblankStatus;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysGetVblankStatus\n"
    ".type sceVideoOutSysGetVblankStatus @function\n"
    "sceVideoOutSysGetVblankStatus:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysGetVblankStatus]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysGetVblankStatus2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysGetVblankStatus2\n"
    ".type sceVideoOutSysGetVblankStatus2 @function\n"
    "sceVideoOutSysGetVblankStatus2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysGetVblankStatus2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysGetVideoOutModeByBusSpecifier;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysGetVideoOutModeByBusSpecifier\n"
    ".type sceVideoOutSysGetVideoOutModeByBusSpecifier @function\n"
    "sceVideoOutSysGetVideoOutModeByBusSpecifier:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysGetVideoOutModeByBusSpecifier]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysHdmiMonitorInfoIsMorpheus;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysHdmiMonitorInfoIsMorpheus\n"
    ".type sceVideoOutSysHdmiMonitorInfoIsMorpheus @function\n"
    "sceVideoOutSysHdmiMonitorInfoIsMorpheus:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysHdmiMonitorInfoIsMorpheus]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysIsModeS3d;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysIsModeS3d\n"
    ".type sceVideoOutSysIsModeS3d @function\n"
    "sceVideoOutSysIsModeS3d:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysIsModeS3d]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysIsSupportedByMonitorInfo_;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysIsSupportedByMonitorInfo_\n"
    ".type sceVideoOutSysIsSupportedByMonitorInfo_ @function\n"
    "sceVideoOutSysIsSupportedByMonitorInfo_:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysIsSupportedByMonitorInfo_]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysIsUserStatusSystemDefault;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysIsUserStatusSystemDefault\n"
    ".type sceVideoOutSysIsUserStatusSystemDefault @function\n"
    "sceVideoOutSysIsUserStatusSystemDefault:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysIsUserStatusSystemDefault]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysIsUserStatusVr;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysIsUserStatusVr\n"
    ".type sceVideoOutSysIsUserStatusVr @function\n"
    "sceVideoOutSysIsUserStatusVr:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysIsUserStatusVr]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysModeIsSystemDefault;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysModeIsSystemDefault\n"
    ".type sceVideoOutSysModeIsSystemDefault @function\n"
    "sceVideoOutSysModeIsSystemDefault:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysModeIsSystemDefault]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysModeIsVr;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysModeIsVr\n"
    ".type sceVideoOutSysModeIsVr @function\n"
    "sceVideoOutSysModeIsVr:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysModeIsVr]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysOpenInternal;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysOpenInternal\n"
    ".type sceVideoOutSysOpenInternal @function\n"
    "sceVideoOutSysOpenInternal:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysOpenInternal]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysReadCrc;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysReadCrc\n"
    ".type sceVideoOutSysReadCrc @function\n"
    "sceVideoOutSysReadCrc:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysReadCrc]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysReadCrc64;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysReadCrc64\n"
    ".type sceVideoOutSysReadCrc64 @function\n"
    "sceVideoOutSysReadCrc64:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysReadCrc64]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysResetAtGpuReset;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysResetAtGpuReset\n"
    ".type sceVideoOutSysResetAtGpuReset @function\n"
    "sceVideoOutSysResetAtGpuReset:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysResetAtGpuReset]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysSetDcePipeMode;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysSetDcePipeMode\n"
    ".type sceVideoOutSysSetDcePipeMode @function\n"
    "sceVideoOutSysSetDcePipeMode:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysSetDcePipeMode]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysSetDimmer;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysSetDimmer\n"
    ".type sceVideoOutSysSetDimmer @function\n"
    "sceVideoOutSysSetDimmer:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysSetDimmer]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysSetDimmer2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysSetDimmer2\n"
    ".type sceVideoOutSysSetDimmer2 @function\n"
    "sceVideoOutSysSetDimmer2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysSetDimmer2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysSetHdrMetadata;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysSetHdrMetadata\n"
    ".type sceVideoOutSysSetHdrMetadata @function\n"
    "sceVideoOutSysSetHdrMetadata:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysSetHdrMetadata]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysSetOverscanRatio;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysSetOverscanRatio\n"
    ".type sceVideoOutSysSetOverscanRatio @function\n"
    "sceVideoOutSysSetOverscanRatio:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysSetOverscanRatio]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysUpdateDisplayParameter;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysUpdateDisplayParameter\n"
    ".type sceVideoOutSysUpdateDisplayParameter @function\n"
    "sceVideoOutSysUpdateDisplayParameter:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysUpdateDisplayParameter]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysUpdatePrivilege;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysUpdatePrivilege\n"
    ".type sceVideoOutSysUpdatePrivilege @function\n"
    "sceVideoOutSysUpdatePrivilege:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysUpdatePrivilege]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutSysUpdateRenderingMode;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutSysUpdateRenderingMode\n"
    ".type sceVideoOutSysUpdateRenderingMode @function\n"
    "sceVideoOutSysUpdateRenderingMode:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutSysUpdateRenderingMode]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutUnlockBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutUnlockBuffer\n"
    ".type sceVideoOutUnlockBuffer @function\n"
    "sceVideoOutUnlockBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutUnlockBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutUnregisterBufferAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutUnregisterBufferAttribute\n"
    ".type sceVideoOutUnregisterBufferAttribute @function\n"
    "sceVideoOutUnregisterBufferAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutUnregisterBufferAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutUnregisterBuffers;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutUnregisterBuffers\n"
    ".type sceVideoOutUnregisterBuffers @function\n"
    "sceVideoOutUnregisterBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutUnregisterBuffers]\n");

static __attribute__ ((used)) void* __ptr_sceVideoOutWaitVblank;
asm(".intel_syntax noprefix\n"
    ".global sceVideoOutWaitVblank\n"
    ".type sceVideoOutWaitVblank @function\n"
    "sceVideoOutWaitVblank:\n"
    "jmp qword ptr [rip + __ptr_sceVideoOutWaitVblank]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceVideoOut", &__handle)) return;
  if(sprx_dlsym(__handle, "v+CRSpiQyVM", &__ptr_sceDbgVideoOutAddOutputModeVr60Privilege)) return;
  if(sprx_dlsym(__handle, "4iy9hG9Du1s", &__ptr_sceVideoOutAddBuffer)) return;
  if(sprx_dlsym(__handle, "twrSaoZ9cJs", &__ptr_sceVideoOutAddBuffer4k2kPrivilege)) return;
  if(sprx_dlsym(__handle, "lm+1oyWKwy0", &__ptr_sceVideoOutAddBufferAnisoPrivilege)) return;
  if(sprx_dlsym(__handle, "MBlv8YWoyOk", &__ptr_sceVideoOutAddBufferAttributeOption)) return;
  if(sprx_dlsym(__handle, "VAlir52gpQI", &__ptr_sceVideoOutAddBufferHdrPrivilege)) return;
  if(sprx_dlsym(__handle, "D3s8DoEnuR4", &__ptr_sceVideoOutAddBufferYccPrivilege)) return;
  if(sprx_dlsym(__handle, "Cxb2w82t7lw", &__ptr_sceVideoOutAddDisplayPositionEvent)) return;
  if(sprx_dlsym(__handle, "HtwSd4H2Tws", &__ptr_sceVideoOutAddDriver)) return;
  if(sprx_dlsym(__handle, "HXzjK9yI30k", &__ptr_sceVideoOutAddFlipEvent)) return;
  if(sprx_dlsym(__handle, "kmSe30JTs+E", &__ptr_sceVideoOutAddOutputModeEvent)) return;
  if(sprx_dlsym(__handle, "keipklF0pMY", &__ptr_sceVideoOutAddPreVblankStartEvent)) return;
  if(sprx_dlsym(__handle, "iT+aFczA7ak", &__ptr_sceVideoOutAddS3dHmdPrivilege)) return;
  if(sprx_dlsym(__handle, "AjtlFa2HRws", &__ptr_sceVideoOutAddSetModeEvent)) return;
  if(sprx_dlsym(__handle, "Ax1Qs3Cm95Q", &__ptr_sceVideoOutAddStereoBuffer)) return;
  if(sprx_dlsym(__handle, "Xru92wHJRmg", &__ptr_sceVideoOutAddVblankEvent)) return;
  if(sprx_dlsym(__handle, "8Lf4Fp1TxA0", &__ptr_sceVideoOutAdjustColor2_)) return;
  if(sprx_dlsym(__handle, "dYDAfB+cJEU", &__ptr_sceVideoOutAdjustColorSpaceConversion_)) return;
  if(sprx_dlsym(__handle, "pv9CI5VC+R0", &__ptr_sceVideoOutAdjustColor_)) return;
  if(sprx_dlsym(__handle, "T0ynQY3mH-0", &__ptr_sceVideoOutClearFlipMaster)) return;
  if(sprx_dlsym(__handle, "uquVH4-Du78", &__ptr_sceVideoOutClose)) return;
  if(sprx_dlsym(__handle, "DYhhWbJSeRg", &__ptr_sceVideoOutColorSettingsSetGamma_)) return;
  if(sprx_dlsym(__handle, "JpAYkddCFjk", &__ptr_sceVideoOutColorSpaceConversionSettingsSetDefaultSdrToHdrConversion_)) return;
  if(sprx_dlsym(__handle, "Yn8KT+VTZaE", &__ptr_sceVideoOutColorSpaceConversionSettingsSetSdrToHdrConversion_)) return;
  if(sprx_dlsym(__handle, "PeUUCAS9Kso", &__ptr_sceVideoOutConfigureLayout)) return;
  if(sprx_dlsym(__handle, "ktP9j1fN-zE", &__ptr_sceVideoOutConfigureOptionsInitialize_)) return;
  if(sprx_dlsym(__handle, "w0hLuNarQxY", &__ptr_sceVideoOutConfigureOutput)) return;
  if(sprx_dlsym(__handle, "2CxY28ewv8g", &__ptr_sceVideoOutConfigureOutputEx)) return;
  if(sprx_dlsym(__handle, "-gYpMonpw2M", &__ptr_sceVideoOutConfigureOutputModeExSubmitDoneUnsafe_)) return;
  if(sprx_dlsym(__handle, "lQh55Q8DUAg", &__ptr_sceVideoOutConfigureOutputModeEx_)) return;
  if(sprx_dlsym(__handle, "N1bEoJ4SRw4", &__ptr_sceVideoOutConfigureOutputMode_)) return;
  if(sprx_dlsym(__handle, "M-JkRj7X+No", &__ptr_sceVideoOutControlHdcpEncryption)) return;
  if(sprx_dlsym(__handle, "fEPEwROdCwM", &__ptr_sceVideoOutCursorDisable)) return;
  if(sprx_dlsym(__handle, "UPZWCH8qTM4", &__ptr_sceVideoOutCursorEnable)) return;
  if(sprx_dlsym(__handle, "HibOtezzT6M", &__ptr_sceVideoOutCursorIsUpdatePending)) return;
  if(sprx_dlsym(__handle, "Se-Zs6koGzk", &__ptr_sceVideoOutCursorSet2xMagnify)) return;
  if(sprx_dlsym(__handle, "jr52f45OlWg", &__ptr_sceVideoOutCursorSetHotSpot)) return;
  if(sprx_dlsym(__handle, "u-9bhWQApq8", &__ptr_sceVideoOutCursorSetImageAddress)) return;
  if(sprx_dlsym(__handle, "N17AK88NdD0", &__ptr_sceVideoOutCursorSetPosition)) return;
  if(sprx_dlsym(__handle, "735GfVO9v2s", &__ptr_sceVideoOutCursorSetPositionStereo)) return;
  if(sprx_dlsym(__handle, "kazBRXPqR7c", &__ptr_sceVideoOutCurveSamplePointsCalc_)) return;
  if(sprx_dlsym(__handle, "gbJ8QxXOR6g", &__ptr_sceVideoOutDeleteDisplayPositionEvent)) return;
  if(sprx_dlsym(__handle, "KA515kD5rAY", &__ptr_sceVideoOutDeleteDriver)) return;
  if(sprx_dlsym(__handle, "-Ozn0F1AFRg", &__ptr_sceVideoOutDeleteFlipEvent)) return;
  if(sprx_dlsym(__handle, "elWQ9vERF-Q", &__ptr_sceVideoOutDeletePreVblankStartEvent)) return;
  if(sprx_dlsym(__handle, "fXCSkDTpJFg", &__ptr_sceVideoOutDeleteSetModeEvent)) return;
  if(sprx_dlsym(__handle, "oNOQn3knW6s", &__ptr_sceVideoOutDeleteVblankEvent)) return;
  if(sprx_dlsym(__handle, "oeNtdmvV4II", &__ptr_sceVideoOutDriverAddEvent)) return;
  if(sprx_dlsym(__handle, "0jGJbNTpSV4", &__ptr_sceVideoOutDriverDecrementBufferLabel)) return;
  if(sprx_dlsym(__handle, "lOR+Nos+Je8", &__ptr_sceVideoOutDriverDeleteEvent)) return;
  if(sprx_dlsym(__handle, "NGyEl5aT4fc", &__ptr_sceVideoOutDriverGetBufferLabelAddress)) return;
  if(sprx_dlsym(__handle, "P1bIHoga4jE", &__ptr_sceVideoOutDriverGetEopHandle)) return;
  if(sprx_dlsym(__handle, "G6peSSDP4iA", &__ptr_sceVideoOutDriverGetFinishedEopHandle)) return;
  if(sprx_dlsym(__handle, "GL8+3RHW5vk", &__ptr_sceVideoOutDriverGetLatestEopHandle)) return;
  if(sprx_dlsym(__handle, "Ztx4b2LhRDk", &__ptr_sceVideoOutDriverIncrementBufferLabel)) return;
  if(sprx_dlsym(__handle, "soAIjspgdt8", &__ptr_sceVideoOutDriverResetBufferLabel)) return;
  if(sprx_dlsym(__handle, "OHnnkrUcShM", &__ptr_sceVideoOutDriverTriggerEvent)) return;
  if(sprx_dlsym(__handle, "5V8YGx9g0UA", &__ptr_sceVideoOutGetBufferInformation)) return;
  if(sprx_dlsym(__handle, "OcQybQejHEY", &__ptr_sceVideoOutGetBufferLabelAddress)) return;
  if(sprx_dlsym(__handle, "IZw2TINic+0", &__ptr_sceVideoOutGetCoredumpOutputMode)) return;
  if(sprx_dlsym(__handle, "W0iQAbGaTBg", &__ptr_sceVideoOutGetCurrentOutputMode_)) return;
  if(sprx_dlsym(__handle, "kGVLc3htQE8", &__ptr_sceVideoOutGetDeviceCapabilityInfo_)) return;
  if(sprx_dlsym(__handle, "p7FV-mU6EM0", &__ptr_sceVideoOutGetDeviceInfoExOts_)) return;
  if(sprx_dlsym(__handle, "k6JLQGuPEYA", &__ptr_sceVideoOutGetDeviceInfoEx_)) return;
  if(sprx_dlsym(__handle, "Mt4QHHkxkOc", &__ptr_sceVideoOutGetEventCount)) return;
  if(sprx_dlsym(__handle, "rWUTcKdkUzQ", &__ptr_sceVideoOutGetEventData)) return;
  if(sprx_dlsym(__handle, "U2JJtSqNKZI", &__ptr_sceVideoOutGetEventId)) return;
  if(sprx_dlsym(__handle, "SbU3dwp80lQ", &__ptr_sceVideoOutGetFlipStatus)) return;
  if(sprx_dlsym(__handle, "hZvzQy2VLKY", &__ptr_sceVideoOutGetHdmiKsvList_)) return;
  if(sprx_dlsym(__handle, "421cr+-5Mus", &__ptr_sceVideoOutGetHdmiMonitorInfoNoMask_)) return;
  if(sprx_dlsym(__handle, "+XlDnumvLVA", &__ptr_sceVideoOutGetHdmiMonitorInfo_)) return;
  if(sprx_dlsym(__handle, "+sXvR1JH9Aw", &__ptr_sceVideoOutGetHdmiRawEdid_)) return;
  if(sprx_dlsym(__handle, "lafoiUl5-5U", &__ptr_sceVideoOutGetMonitorInfo)) return;
  if(sprx_dlsym(__handle, "utPrVdxio-8", &__ptr_sceVideoOutGetOutputStatus)) return;
  if(sprx_dlsym(__handle, "y4l-VBLsNio", &__ptr_sceVideoOutGetPortStatusInfo)) return;
  if(sprx_dlsym(__handle, "4TPW3H2f-lM", &__ptr_sceVideoOutGetPortStatusInfoByBusSpecifier_)) return;
  if(sprx_dlsym(__handle, "SDoPm73tOyI", &__ptr_sceVideoOutGetPortStatusInfo_)) return;
  if(sprx_dlsym(__handle, "6kPnj51T62Y", &__ptr_sceVideoOutGetResolutionStatus)) return;
  if(sprx_dlsym(__handle, "+tB28CUr9W0", &__ptr_sceVideoOutGetStatusForWebcore)) return;
  if(sprx_dlsym(__handle, "1FZBKy8HeNU", &__ptr_sceVideoOutGetVblankStatus)) return;
  if(sprx_dlsym(__handle, "UazrNFzZPRU", &__ptr_sceVideoOutGetVideoOutModeByBusSpecifier_)) return;
  if(sprx_dlsym(__handle, "XNtZ16LIhf0", &__ptr_sceVideoOutHdmiMonitorInfoIsSupportedHdcpVersion)) return;
  if(sprx_dlsym(__handle, "WBZrUaQY+EU", &__ptr_sceVideoOutHdmiMonitorInfoIsSupportedVideoOutMode_)) return;
  if(sprx_dlsym(__handle, "+I4K03i3EL0", &__ptr_sceVideoOutInitializeOutputOptions)) return;
  if(sprx_dlsym(__handle, "zgXifHT9ErY", &__ptr_sceVideoOutIsFlipPending)) return;
  if(sprx_dlsym(__handle, "Nv8c-Kb+DUM", &__ptr_sceVideoOutIsOutputSupported)) return;
  if(sprx_dlsym(__handle, "7ifZFxWJ9Q4", &__ptr_sceVideoOutLockBuffer)) return;
  if(sprx_dlsym(__handle, "pjkDsgxli6c", &__ptr_sceVideoOutModeSetAny_)) return;
  if(sprx_dlsym(__handle, "Up36PTk687E", &__ptr_sceVideoOutOpen)) return;
  if(sprx_dlsym(__handle, "ZX7C79uOujU", &__ptr_sceVideoOutRazorAddCallback)) return;
  if(sprx_dlsym(__handle, "hGcTks-qqIU", &__ptr_sceVideoOutRazorRecallCallbacks)) return;
  if(sprx_dlsym(__handle, "zUDW7kIFclI", &__ptr_sceVideoOutRazorRemoveCallback)) return;
  if(sprx_dlsym(__handle, "EJQifjOp8s4", &__ptr_sceVideoOutRegisterBufferAttribute)) return;
  if(sprx_dlsym(__handle, "w3BY+tAEiQY", &__ptr_sceVideoOutRegisterBuffers)) return;
  if(sprx_dlsym(__handle, "rKBUtgRrtbk", &__ptr_sceVideoOutRegisterBuffers2)) return;
  if(sprx_dlsym(__handle, "lCTCOogRbk0", &__ptr_sceVideoOutRegisterStereoBuffers)) return;
  if(sprx_dlsym(__handle, "H8teLntGkWs", &__ptr_sceVideoOutRemoveBuffer)) return;
  if(sprx_dlsym(__handle, "k4Ak+e2D1Hg", &__ptr_sceVideoOutRemoveBufferAttributeOption)) return;
  if(sprx_dlsym(__handle, "-zRnJ7WoWSY", &__ptr_sceVideoOutSetAlphaControl)) return;
  if(sprx_dlsym(__handle, "zILy8t+5bPo", &__ptr_sceVideoOutSetBlankAfterResume)) return;
  if(sprx_dlsym(__handle, "i6-sR91Wt-4", &__ptr_sceVideoOutSetBufferAttribute)) return;
  if(sprx_dlsym(__handle, "PjS5uASwcV8", &__ptr_sceVideoOutSetBufferAttribute2)) return;
  if(sprx_dlsym(__handle, "KHBNAkJhT64", &__ptr_sceVideoOutSetContentType)) return;
  if(sprx_dlsym(__handle, "18NPivA-byc", &__ptr_sceVideoOutSetDisplayEventPosition)) return;
  if(sprx_dlsym(__handle, "WkYtyOg30do", &__ptr_sceVideoOutSetFlipMaster)) return;
  if(sprx_dlsym(__handle, "CBiu4mCE1DA", &__ptr_sceVideoOutSetFlipRate)) return;
  if(sprx_dlsym(__handle, "emayD9LHYsc", &__ptr_sceVideoOutSetGamutMetadata_)) return;
  if(sprx_dlsym(__handle, "pA8xxaySl7A", &__ptr_sceVideoOutSetGlobalBlendSpace)) return;
  if(sprx_dlsym(__handle, "CxUz3nU06NE", &__ptr_sceVideoOutSetToneMap_)) return;
  if(sprx_dlsym(__handle, "MTxxrOCeSig", &__ptr_sceVideoOutSetWindowModeMargins)) return;
  if(sprx_dlsym(__handle, "IOdgHlCGU-k", &__ptr_sceVideoOutSubmitChangeBufferAttribute)) return;
  if(sprx_dlsym(__handle, "HuViW4HnrOw", &__ptr_sceVideoOutSubmitChangeBufferAttribute2)) return;
  if(sprx_dlsym(__handle, "j8xl+92A0q4", &__ptr_sceVideoOutSubmitEopFlip)) return;
  if(sprx_dlsym(__handle, "U46NwOiJpys", &__ptr_sceVideoOutSubmitFlip)) return;
  if(sprx_dlsym(__handle, "X8FN-5Nk-yE", &__ptr_sceVideoOutSysAddSetModeEvent)) return;
  if(sprx_dlsym(__handle, "fYWVVDKZOCk", &__ptr_sceVideoOutSysAddSetModeEvent2)) return;
  if(sprx_dlsym(__handle, "Ek+VR4lcJQI", &__ptr_sceVideoOutSysAddVblankEvent)) return;
  if(sprx_dlsym(__handle, "Am8Hlr7tlxA", &__ptr_sceVideoOutSysAddVblankEvent2)) return;
  if(sprx_dlsym(__handle, "dIb9LsrpkQM", &__ptr_sceVideoOutSysClose)) return;
  if(sprx_dlsym(__handle, "FDTOhhPHtps", &__ptr_sceVideoOutSysConfigureLayout)) return;
  if(sprx_dlsym(__handle, "ofkhJRiQua0", &__ptr_sceVideoOutSysConfigureOutput)) return;
  if(sprx_dlsym(__handle, "ox3wD142jZQ", &__ptr_sceVideoOutSysConfigureOutputMode)) return;
  if(sprx_dlsym(__handle, "6L0-A5piudQ", &__ptr_sceVideoOutSysCursorDisable)) return;
  if(sprx_dlsym(__handle, "xwhyGPZkW6w", &__ptr_sceVideoOutSysCursorEnable)) return;
  if(sprx_dlsym(__handle, "ekwMB-Ftq18", &__ptr_sceVideoOutSysCursorIsUpdatePending)) return;
  if(sprx_dlsym(__handle, "+epU+rgObyw", &__ptr_sceVideoOutSysCursorObtain)) return;
  if(sprx_dlsym(__handle, "QSmT3attiVg", &__ptr_sceVideoOutSysCursorRelease)) return;
  if(sprx_dlsym(__handle, "fZgBeiGqE+c", &__ptr_sceVideoOutSysCursorSetPosition)) return;
  if(sprx_dlsym(__handle, "iwsJdAZCg34", &__ptr_sceVideoOutSysDeleteVblankEvent)) return;
  if(sprx_dlsym(__handle, "2EBuouuYKgM", &__ptr_sceVideoOutSysDeleteVblankEvent2)) return;
  if(sprx_dlsym(__handle, "7VSZJxxcTL8", &__ptr_sceVideoOutSysGetBus)) return;
  if(sprx_dlsym(__handle, "IpMhRnVgJUU", &__ptr_sceVideoOutSysGetColorConversionStatus)) return;
  if(sprx_dlsym(__handle, "IysRiVOGIVM", &__ptr_sceVideoOutSysGetCurrentOutputMode)) return;
  if(sprx_dlsym(__handle, "2sgenMqwczM", &__ptr_sceVideoOutSysGetDeviceInfo)) return;
  if(sprx_dlsym(__handle, "21sS8EU45cw", &__ptr_sceVideoOutSysGetFlipStatus)) return;
  if(sprx_dlsym(__handle, "vMLWuJckGv0", &__ptr_sceVideoOutSysGetMonitorInfo_)) return;
  if(sprx_dlsym(__handle, "8XGijEoThE0", &__ptr_sceVideoOutSysGetResolutionStatus)) return;
  if(sprx_dlsym(__handle, "qLDCAl8ygCw", &__ptr_sceVideoOutSysGetResolutionStatus2)) return;
  if(sprx_dlsym(__handle, "d1AjT2uZJn0", &__ptr_sceVideoOutSysGetVblankStatus)) return;
  if(sprx_dlsym(__handle, "iYrCszX93AM", &__ptr_sceVideoOutSysGetVblankStatus2)) return;
  if(sprx_dlsym(__handle, "AAELy8Yc3Mc", &__ptr_sceVideoOutSysGetVideoOutModeByBusSpecifier)) return;
  if(sprx_dlsym(__handle, "3-9DXFGVg0M", &__ptr_sceVideoOutSysHdmiMonitorInfoIsMorpheus)) return;
  if(sprx_dlsym(__handle, "iUigHJ2op4M", &__ptr_sceVideoOutSysIsModeS3d)) return;
  if(sprx_dlsym(__handle, "mfxElr79O7Q", &__ptr_sceVideoOutSysIsSupportedByMonitorInfo_)) return;
  if(sprx_dlsym(__handle, "O57F5ikhGxo", &__ptr_sceVideoOutSysIsUserStatusSystemDefault)) return;
  if(sprx_dlsym(__handle, "4XsQdhiOaAc", &__ptr_sceVideoOutSysIsUserStatusVr)) return;
  if(sprx_dlsym(__handle, "5Y8uUbGMio0", &__ptr_sceVideoOutSysModeIsSystemDefault)) return;
  if(sprx_dlsym(__handle, "QEiuHxjungc", &__ptr_sceVideoOutSysModeIsVr)) return;
  if(sprx_dlsym(__handle, "kP4l+nyBjRA", &__ptr_sceVideoOutSysOpenInternal)) return;
  if(sprx_dlsym(__handle, "E8C608-pFng", &__ptr_sceVideoOutSysReadCrc)) return;
  if(sprx_dlsym(__handle, "eBvoaLwfBBQ", &__ptr_sceVideoOutSysReadCrc64)) return;
  if(sprx_dlsym(__handle, "djc8fOzOXxk", &__ptr_sceVideoOutSysResetAtGpuReset)) return;
  if(sprx_dlsym(__handle, "jvPer4hz+UU", &__ptr_sceVideoOutSysSetDcePipeMode)) return;
  if(sprx_dlsym(__handle, "OOF0YO73GTA", &__ptr_sceVideoOutSysSetDimmer)) return;
  if(sprx_dlsym(__handle, "X7tWmHNtoKg", &__ptr_sceVideoOutSysSetDimmer2)) return;
  if(sprx_dlsym(__handle, "-ka14VvHSX0", &__ptr_sceVideoOutSysSetHdrMetadata)) return;
  if(sprx_dlsym(__handle, "nMbAqI1ty8w", &__ptr_sceVideoOutSysSetOverscanRatio)) return;
  if(sprx_dlsym(__handle, "UFDoqv4XXC0", &__ptr_sceVideoOutSysUpdateDisplayParameter)) return;
  if(sprx_dlsym(__handle, "Jl91AhxKc0w", &__ptr_sceVideoOutSysUpdatePrivilege)) return;
  if(sprx_dlsym(__handle, "4G37EIMMD+Q", &__ptr_sceVideoOutSysUpdateRenderingMode)) return;
  if(sprx_dlsym(__handle, "amghnA-Ev5s", &__ptr_sceVideoOutUnlockBuffer)) return;
  if(sprx_dlsym(__handle, "SRQSpP4QK5U", &__ptr_sceVideoOutUnregisterBufferAttribute)) return;
  if(sprx_dlsym(__handle, "N5KDtkIjjJ4", &__ptr_sceVideoOutUnregisterBuffers)) return;
  if(sprx_dlsym(__handle, "j6RaAUlaLv0", &__ptr_sceVideoOutWaitVblank)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
