#   Copyright (C) 2023 John Törnblom
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not see
# <http://www.gnu.org/licenses/>.

PYTHON  ?= python3
DESTDIR ?= /opt/ps5-payload-sdk

CC := clang
LD := ld.lld

CFLAGS  := -ffreestanding -fno-builtin -nostdlib
CFLAGS  += -target x86_64-sie-ps5 -fno-plt -fno-stack-protector

SPRXS := $(wildcard *.sprx)
STUBS := $(SPRXS:.sprx=.c)

SOURCES  := $(wildcard *.c)
SHARED   := $(SOURCES:.c=.so)

NID_DB_URL := https://raw.githubusercontent.com/astrelsky/GhidraOrbis/master/data/nid_db.xml

all: $(SOURCES) $(SHARED)

stubs: nid_db.xml $(STUBS)

nid_db.xml:
	wget -O $@ $(NID_DB_URL)

%.c: %.sprx
	$(PYTHON) genstub.py $^ > $@

%.o: %.c
	$(CC) -c $(CFLAGS) -o $@ $^

%.so: %.o
	$(LD) -shared -o $@ $<

clean:
	rm -f *.o *.so nid_db.xml

install: $(SHARED)
	install -d $(DESTDIR)/usr/lib
	install $(SHARED) $(DESTDIR)/usr/lib
